#pragma once
#include <array>
#include <cstdint>
namespace salek::giti {
struct Identity { const char* number; const char* name; const char* branch; const char* voice; const char* power; const char* mood; const char* special; std::uint32_t colorA; std::uint32_t colorB; };
inline constexpr std::array<Identity, 50> identities {{
    { "001", "The First Breath", "Breath", "A single human breath across a reed", "Clears every stray noise from a space until one clean tone remains", "origin", "THE ORIGINAL", 0xff3dffecu, 0xff8f5cffu },
    { "002", "Santur Rain", "Strings", "Hammered dulcimer struck with light mallets", "Sympathetic overtones that untangle knotted thoughts", "bright", "", 0xff6a5cffu, 0xffff3fa6u },
    { "003", "Cradle Song", "Voice", "A mother's lullaby hummed low", "A rocking pulse that quiets a restless mind", "sleep", "", 0xffff3fd1u, 0xffd02a3cu },
    { "004", "Daf Heart", "Pulse", "A large frame drum with jingling rings", "A steady beat that entrains a hurried heart", "steady", "", 0xffd02a61u, 0xff2fbf8fu },
    { "005", "Spring Bell", "Earth & Water", "A single drop of water in a cold bell", "A pure ring that resets a listener's attention", "clear", "", 0xff2fbf6fu, 0xff3de6ffu },
    { "006", "Ney Dawn", "Breath", "A shepherd's reed flute, breathy and warm", "A rising pitch that lifts fog from a troubled mind", "first light", "", 0xff3dfff6u, 0xffff3fa6u },
    { "007", "Tar Oath", "Strings", "A long-necked lute with a warm gut-string voice", "A chord that makes promises feel safe to keep", "trust", "", 0xff725cffu, 0xffd02a3cu },
    { "008", "Throat Star", "Voice", "Overtone throat singing, two notes at once", "Splits one voice into a bright ring that focuses attention", "overtone", "", 0xffff3fc8u, 0xff2fbf8fu },
    { "009", "Tombak Rain", "Pulse", "A goblet drum played with fingertips", "Rapid patter that scatters worry like drops", "patter", "", 0xffd02a59u, 0xff3de6ffu },
    { "010", "Cave Choir", "Earth & Water", "Voices of stone and dripping water", "Natural reverb that turns a whisper into a sanctuary", "hollow", "", 0xff2fbf76u, 0xff8f5cffu },
    { "011", "Glass Whisper", "Breath", "Whispered consonants with no pitch at all", "A hush so precise that a shouting room lowers its voice to hear it", "hush", "", 0xff3dfeffu, 0xffd02a3cu },
    { "012", "Setar Thread", "Strings", "Four thin strings, barely touched", "The quietest sound in the system, and the hardest to ignore", "tender", "", 0xff7b5cffu, 0xff2fbf8fu },
    { "013", "Mother Tongue", "Voice", "Spoken vowels in a language no one can name", "Vowel colors that make a stranger feel understood", "home", "", 0xffff3fbeu, 0xff3de6ffu },
    { "014", "Walk, Not March", "Pulse", "Footsteps on a wooden floor", "A pace that invites and never commands", "gentle", "", 0xffd02a51u, 0xff8f5cffu },
    { "015", "River Glass", "Earth & Water", "Water moving over glass pebbles", "Gentle turbulence that washes worry downstream", "flow", "", 0xff2fbf7du, 0xffff3fa6u },
    { "016", "Kite Wind", "Breath", "Wind pulled through a mountain pass", "Carries one small signal across a valley of noise", "open sky", "", 0xff3df5ffu, 0xff2fbf8fu },
    { "017", "Kamancheh Tide", "Strings", "A bowed spike fiddle with a singing, nasal glide", "A long bowed line that carries sorrow out like a tide", "grief", "", 0xff835cffu, 0xff3de6ffu },
    { "018", "Choir of Salt", "Voice", "A weathered coastal choir in slow harmony", "Sustained chords that hold a crowd steady", "harbor", "", 0xffff3fb4u, 0xff8f5cffu },
    { "019", "Zarb Ember", "Pulse", "Fingers on a warm goblet drum, slowly building", "A slow build that turns hesitation into motion", "kindling", "", 0xffd02a48u, 0xffff3fa6u },
    { "020", "Rain Loom", "Earth & Water", "Rain on tin, leaves and clay pots", "Patterned rainfall that cools an overheated room", "soak", "", 0xff2fbf84u, 0xffd02a3cu },
    { "021", "Frost Reed", "Breath", "A cold bone flute with a hollow, silver edge", "Freezes panic into a calm that holds its shape", "stillness", "", 0xff3debffu, 0xff8f5cffu },
    { "022", "Oud Ember", "Strings", "A fretless lute, dark and round", "Low warmth that softens a hardened stare", "dusk", "", 0xff8b5cffu, 0xffff3fa6u },
    { "023", "Ghazal Bloom", "Voice", "A sung poem with ornamented melodic turns", "Melodic ornaments that turn longing into resolve", "longing", "", 0xffff3fabu, 0xffd02a3cu },
    { "024", "Anvil Psalm", "Pulse", "A hammered anvil struck like a bell", "Each strike turns raw anger into a tuned bell tone", "forge", "", 0xffd02a40u, 0xff2fbf8fu },
    { "025", "Forest Throat", "Earth & Water", "Wood, birdsong and bark resonances", "Living texture that reminds people they belong here", "green", "", 0xff2fbf8bu, 0xff3de6ffu },
    { "026", "Monsoon Sigh", "Breath", "One long human exhale, slowly falling", "Loosens tight chests and unclenches jaws", "release", "", 0xff3de1ffu, 0xffff3fa6u },
    { "027", "Barbat Lantern", "Strings", "An ancient lute plucked in patient patterns", "A repeating figure that guides the lost toward a shared beat", "guiding", "", 0xff935cffu, 0xffd02a3cu },
    { "028", "Call at Dusk", "Voice", "A long evening call over rooftops", "A single held note that gathers scattered people", "gathering", "", 0xffff3fa1u, 0xff2fbf8fu },
    { "029", "Stone Drum", "Pulse", "A drum of carved stone, dry and deep", "A deep thud that reminds a room of solid ground", "ancient", "", 0xffd02a38u, 0xff3de6ffu },
    { "030", "Salt Desert Hum", "Earth & Water", "A dry wind hum across a salt flat", "An endless low tone that makes worry feel small", "vast", "", 0xff2fbf93u, 0xff8f5cffu },
    { "031", "Cloud Choir", "Breath", "A hundred layered breaths with ringing overtones", "Overtone shimmer that dissolves tension before it becomes anger", "shimmer", "", 0xff3dd7ffu, 0xffd02a3cu },
    { "032", "Qanun Loom", "Strings", "A plucked zither with rippling strings", "Weaves neighboring notes until they agree with each other", "weaving", "", 0xff9b5cffu, 0xff2fbf8fu },
    { "033", "Laughter Loom", "Voice", "Real laughter, pitched and layered", "Contagious rhythm that breaks the grip of dread", "warmth", "", 0xffff3f98u, 0xff3de6ffu },
    { "034", "Heartbeat Chorus", "Pulse", "A thousand heartbeats layered", "Brings a crowd's pulses into one slow rhythm", "kin", "", 0xffd02a30u, 0xff8f5cffu },
    { "035", "Tide Ledger", "Earth & Water", "Sea swells recorded over a thousand years", "Slow waves that let old grief wash up and out", "memory", "", 0xff2fbf9au, 0xffff3fa6u },
    { "036", "Silent Horn", "Breath", "A brass horn that plays only the silence after", "The pause that ends an argument before the next word", "pause", "", 0xff3dceffu, 0xff2fbf8fu },
    { "037", "Chang Cathedral", "Strings", "A great harp resonating like stone arches", "Builds a space so resonant that quarrels echo into laughter", "vaulted", "", 0xffa35cffu, 0xff3de6ffu },
    { "038", "Hum of Forgiveness", "Voice", "A closed-mouth hum, low and steady", "A low resonance felt in the chest that lets anger settle", "soft", "", 0xffff3f8eu, 0xff8f5cffu },
    { "039", "Sub Vow", "Pulse", "A bass tone felt through the floor", "Frequencies below hearing that let fear leave the body", "depth", "", 0xffd02d2au, 0xffff3fa6u },
    { "040", "Seed Chime", "Earth & Water", "Tiny wooden chimes like seeds in a gourd", "A soft rattle that plants the idea of a better tomorrow", "promise", "", 0xff2fbfa1u, 0xffd02a3cu },
    { "041", "Sky Lung", "Breath", "A vast slow inhale, felt more than heard", "Slows a whole crowd's breathing into the same rhythm", "unison", "", 0xff3dc4ffu, 0xff8f5cffu },
    { "042", "Rubab Storm", "Strings", "A hand-plucked lute that thunders, then settles", "A rush of overtones that overwhelms fear, then leaves calm", "surge", "", 0xffac5cffu, 0xffff3fa6u },
    { "043", "Ten Thousand Voices", "Voice", "A crowd singing one line in many pitches", "Turns disagreement into harmony by giving everyone a note", "many", "", 0xffff3f84u, 0xffd02a3cu },
    { "044", "Thunder Lullaby", "Pulse", "Distant thunder shaped into a rocking meter", "Turns a storm into a lullaby, one roll at a time", "storm calm", "", 0xffd0352au, 0xff2fbf8fu },
    { "045", "Root Drone", "Earth & Water", "A drone from resonant roots and soil", "A deep tone that anchors people who feel adrift", "grounded", "", 0xff2fbfa8u, 0xff3de6ffu },
    { "046", "Last Horizon", "Breath", "The breath of an entire sky", "Lets a distant listener feel close to everyone else", "distance", "", 0xff3dbaffu, 0xffff3fa6u },
    { "047", "Nine Thousand Strings", "Strings", "Every string of the old world, bowed and plucked at once", "One harmonic field where no two sounds can stay in conflict", "constellation", "", 0xffb45cffu, 0xffd02a3cu },
    { "048", "The Sung Name", "Voice", "One name sung until it becomes a melody", "Makes every listener feel seen", "recognition", "", 0xffff3f7bu, 0xff2fbf8fu },
    { "049", "Pulse of Succession", "Pulse", "A slow drum counting down to the next generation", "A rhythm that teaches the next machine when to begin", "handover", "", 0xffd03d2au, 0xff3de6ffu },
    { "050", "The Last Voice", "Earth & Water", "The unison of all forty-nine before it", "One chord made of every GITI voice, handing the world to KAYHAN", "succession", "FINAL EVOLUTION OF GENESIS", 0xff2fbfafu, 0xff8f5cffu },
}};
} // namespace salek::giti
